title: Grant Matthew Gilson # your name (or website title) here
logo: "/images/pusheen.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Computer Science Undergraduate at UC Davis 
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/grantmgilson/">LinkedIn</a>
  <a href="images/Industry Resume.pdf">
  
theme: jekyll-theme-minimal
google_analytics: UA-171579657-1 # your Google Analytics tracking ID here
