title: Grant Matthew Gilson # your name (or website title) here
logo: "/images/pusheenPFP.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Pursuing Degree of Computer Science at the University of California Davis
  <br><br>
  <a href="https://www.linkedin.com/in/grantmgilson/">LinkedIn</a>
  <br><br>
  <a href="images/Industry Resume.pdf">Resume</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-171579657-1 # your Google Analytics tracking ID here
